In [2]:
########Simple Forward Propagation##########
import numpy as np

In [3]:
X=np.array([[0,0],[0,1],[1,0],[1,1]])
Y=np.array([[0,0,0,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [4]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [5]:
weights=2*np.random.random((2,1))-1
bias=2*np.random.random(1)-1
weights
#The weights are randomly assigned between 0 and 1
#The weights should ideally be between 0 and 1

array([[ 0.51181555],
       [ 0.67658502]])

In [6]:
output0=X
output=sigmoid(np.dot(X,weights)+bias)
output

array([[ 0.63805829],
       [ 0.77617812],
       [ 0.74625963],
       [ 0.85262595]])

In [7]:
####Forward Propagation with 1 hidden layer#####

In [8]:
#wh-hidden layer weights
#bh-hidden layer bias
#wo-outer layer weight
#bo-outer layer bias
wh=2*np.random.random([2,2])-1
bh=2*np.random.random([1,2])-1
wo=2*np.random.random([2,1])-1
bo=2*np.random.random([1,1])-1

In [9]:
output0=X
outputHidden=sigmoid(np.dot(X,wh)+bh)
output=sigmoid(np.dot(outputHidden,wo)+bo)
output

array([[ 0.33786671],
       [ 0.36317461],
       [ 0.33807744],
       [ 0.36102486]])